[package]
name = "second_crate"
version = "0.1.1"
edition = "2021"
description = "A test crate for Docify functionality"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/second_crate"


[dependencies]
docify_clone = "0.0.2"
